// File generated by flutterfire cli.
// To regenerate this file, run flutterfire configure.
//
// Run this command to generate with your Firebase project config:
// flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCvLSdsCrPU3EXcmwJK8d1orV79737vso',
    appId: '1:394675648791:web:911ee92784672ceef21f52',
    messagingSenderId: '394675648791',
    projectId: 'gtcrm-857e1',
    authDomain: 'gtcrm-857e1.firebaseapp.com',
    storageBucket: 'gtcrm-857e1.firebasestorage.app',
    measurementId: 'G-PX31NMW3EB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCqvjzSuomkJZA0yr2U5Y0jMz5cMRc-RE',
    appId: '1:394675648791:android:a7f5c176a2e0f459f21f52',
    messagingSenderId: '394675648791',
    projectId: 'gtcrm-857e1',
    storageBucket: 'gtcrm-857e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtOwVs878WGGF8P2UO9eBLEcAuY8MRbAk',
    appId: '1:394675648791:ios:32bc830a7e79a8b4f21f52',
    messagingSenderId: '394675648791',
    projectId: 'gtcrm-857e1',
    storageBucket: 'gtcrm-857e1.firebasestorage.app',
    iosBundleId: 'com.gitakshmi.edupathpro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtOwVs878WGGF8P2UO9eBLEcAuY8MRbAk',
    appId: '1:394675648791:ios:6308527eca12bc56f21f52',
    messagingSenderId: '394675648791',
    projectId: 'gtcrm-857e1',
    storageBucket: 'gtcrm-857e1.firebasestorage.app',
    iosBundleId: 'com.example.gtcrm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCvLSdsCrPU3EXcmwJK8d1orV79737vso',
    appId: '1:394675648791:web:d06436ad0eac47e1f21f52',
    messagingSenderId: '394675648791',
    projectId: 'gtcrm-857e1',
    authDomain: 'gtcrm-857e1.firebaseapp.com',
    storageBucket: 'gtcrm-857e1.firebasestorage.app',
    measurementId: 'G-8B6ER40D0S',
  );
}
